### ISSUE TITLE
Move from redis to valkey

### ISSUE THREAD

**Issue by mmacata** [actinia-org/actinia-core#573]
Redis won't be open source anymore from version 7.4 . Therefore move from redis to valkey.

- [x] functional adjustments in actinia-docker https://github.com/actinia-org/actinia-docker/pull/89
- [x] functional adjustments in actinia-core - replace lib redis with valkey https://github.com/actinia-org/actinia-core/pull/585
- [x] functional adjustments in actinia-core for tests (separate or with step(s) below (see PR #585, #600)
- [x] semantic adjustments in actinia-core - replace occurence of word `redis` with functional description instead of software name, e.g. `kvstore` or `kvdb` #602,  #601
    Examples:
    ```
    conf.REDIS_QUEUE_SERVER_URL
    from .redis_resources import RedisResourceInterface
    actinia-core.redis_fluentd_logger_base
    actinia_core.core.redis_api_log
    self.redis_server.lrange
    class RedisFluentLoggerBase(object)
    ```
- [x] necessary + semantic adjustments in actinia plugins and actinia-docker and actinia-api (e.g. config) after semantic adjustments in actinia-core see #604 
- [ ] ...
- [ ] Bonus: Split up into multiple valkey DBs dedicated to one purpose to prepare later refactoring.

**Comment by mmacata** [comment]
Same was done for `mundialis/actinia` Dockerimage:

```diff
diff --git a/actinia-alpine/Dockerfile b/actinia-alpine/Dockerfile
index c3f5065..20c5f9b 100644
--- a/actinia-alpine/Dockerfile
+++ b/actinia-alpine/Dockerfile
@@ -6,7 +6,7 @@ WORKDIR /src/actinia-docker
 RUN git describe --dirty --tags --long --first-parent > /actinia-docker-version.txt
 
 FROM mundialis/actinia:alpine-dependencies-2025-03-14 as base
-FROM osgeo/grass-gis:main-alpine as grass
+FROM grass-py3-pdal:g83-alpine3.21 as grass
 FROM mundialis/esa-snap:s1tbx-31e0b3d as snap
 
 FROM base
@@ -44,8 +44,8 @@ COPY --from=grass /usr/local/grass/etc/proj/ /etc/proj/
 COPY --from=grass /usr/local/grass/etc/colors/ /etc/colors/
 RUN pip3 install --upgrade pip six grass-session --ignore-installed six
 # RUN ln -s /usr/local/grass `grass --config path`
-RUN ln -s /usr/local/grass /usr/local/grass85
-RUN grass --tmp-project EPSG:4326 --exec g.version -rge && \
+RUN ln -s /usr/local/grass /usr/local/grass83
+RUN grass --tmp-location EPSG:4326 --exec g.version -rge && \
     pdal --version && \
     python3 --version
 
@@ -61,7 +61,7 @@ RUN git clone https://github.com/NVE/actinia_modules_nve.git /src/nve-addons
 
 COPY grass_addons_list.csv /src/grass_addons_list.csv
 
-RUN while IFS=, read -r ADDON SERVER; do if [[ $ADDON != "#*" ]]; then unset URL; test -z $SERVER || URL="url=$SERVER"; grass --tmp-project EPSG:4326 --exec g.extension -s extension=$ADDON $URL;fi;done < /src/grass_addons_list.csv
+RUN while IFS=, read -r ADDON SERVER; do if [[ $ADDON != "#*" ]]; then unset URL; test -z $SERVER || URL="url=$SERVER"; grass --tmp-location EPSG:4326 --exec g.extension -s extension=$ADDON $URL;fi;done < /src/grass_addons_list.csv
 
 # actinia-core and plugins installation
 WORKDIR /build
@@ -138,6 +138,9 @@ RUN cd gdal-grass \
 && cmake --install build
 RUN cd .. && rm -rf gdal-grass
 
+# TODO: remove when included in dependency image
+RUN apk add valkey valkey-cli
+
 ENTRYPOINT ["/bin/sh"]
 CMD ["/src/start.sh"]
```

and pushed to `mundialis/actinia-core:grass8.3`
